CREATE TABLE IF NOT EXISTS User (
    id         INTEGER       GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username   VARCHAR2(64)  UNIQUE NOT NULL,
    pword      VARCHAR2(128) NOT NULL,
    first_name VARCHAR2(50)  NOT NULL,
    surname    VARCHAR2(50)  NOT NULL,
    loc        INTEGER       NOT NULL REFERENCES Loc,
    birthdate  DATE          NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Comment (
    id          INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0, 
    user_id     INTEGER  NOT NULL REFERENCES User,
    post_date   DATETIME NOT NULL,
    contents    VARCHAR2(200),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CommentRating (
    id          INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0,
    stars       INTEGER  CHECK (stars >= 0 && stars <= 5),
    num_reviews INTEGER  CHECK (num_reviews >= 0),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Claim (
    id         INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0, 
    user_id    INTEGER  NOT NULL REFERENCES User,
    flight_id  INTEGER  NOT NULL REFERENCES Flight,
    post_date  DATETIME NOT NULL,
    company_id INTEGER  NOT NULL REFERENCES CompensationCompany,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PlannedFlight (
    id         INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0, 
    user_id  INTEGER NOT NULL REFERENCES User,
    dep_date DATE    NOT NULL,
    arr_date DATE    NOT NULL,
    dep_loc  INTEGER NOT NULL REFERENCES Loc,
    arr_loc  INTEGER NOT NULL REFERENCES Loc,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CompensationCompany (
    id          INTEGER      GENERATED ALWAYS AS IDENTITY START WITH 0, 
    cname       VARCHAR2(20) NOT NULL,
    success_fee NUMBER       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CompanyRating (
    id          INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0,
    stars       INTEGER  CHECK (stars >= 0 && stars <= 5),
    num_reviews INTEGER  CHECK (num_reviews >= 0),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Airline (
    id            INTEGER GENERATED ALWAYS AS IDENTITY START WITH 0, 
    points_per_km INTEGER DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS AirlineRating (
    id          INTEGER  GENERATED ALWAYS AS IDENTITY START WITH 0,
    stars       INTEGER  CHECK (stars >= 0 && stars <= 5),
    num_reviews INTEGER  CHECK (num_reviews >= 0),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS FlightAttending (
    flight_id    INTEGER NOT NULL REFERENCES Flight,
    attendant_id INTEGER NOT NULL REFERENCES User,
    PRIMARY KEY (flight_id, attendant_id)
);

CREATE TABLE IF NOT EXISTS Airport (
    id   INTEGER      NOT NULL,
    city VARCHAR2(85) NOT NULL
);

CREATE TABLE IF NOT EXISTS Flight (
    id                    INTEGER  NOT NULL CHECK (id >= 0), /* ECTRL ID */
    a_dep                 INTEGER  NOT NULL REFERENCES Airport,
    a_des                 INTEGER  NOT NULL REFERENCES Airport,
    filed_off_block_time  DATETIME NOT NULL, 
    actual_off_block_time DATETIME NOT NULL, 
    filed_arrival_time    DATETIME NOT NULL, 
    actual_arrival_time   DATETIME NOT NULL,
    actual_distance_flown INTEGER  NOT NULL CHECK (actual_distance_flown >= 0)
);

